
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: caio
    password: caio
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update